<template>
  <footer class="editor-footer">
    <!-- Language Selection -->
    <b-field v-if="activeDocumentMode" class="editor-footer-input">
      <b-select
        icon="web"
        :value="activeDocumentMode.caption"
        size="is-small"
        @input="changeLanguage"
      >
        <option
          v-for="language in languages"
          :key="language"
          :value="language"
        >
          {{ language }}
        </option>
      </b-select>
    </b-field>

    <!-- Theme Selection -->
    <b-field class="editor-footer-input">
      <b-select
        icon="palette"
        :value="selectedTheme"
        size="is-small"
        @input="changeTheme"
      >
        <option
          v-for="theme in themes"
          :key="theme"
          :value="theme"
        >
          {{ theme }}
        </option>
      </b-select>
    </b-field>
  </footer>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex'
import { modesByName, modes } from '~/plugins/ace-modelist'

export default {
  name: 'EditorFooter',
  props: {
    activeDocument: {
      type: String,
      default: null
    }
  },
  data () {
    return {
      // Array generated by running command in ~/node_modules/brace/theme
      // echo \[$(for file in *; echo \'$(echo $file | cut -d '.' -f 1)\',)\]
      themes: ['ambiance', 'chaos', 'chrome', 'clouds', 'clouds_midnight', 'cobalt', 'crimson_editor', 'dawn', 'dracula', 'dreamweaver', 'eclipse', 'github', 'gob', 'gruvbox', 'idle_fingers', 'iplastic', 'katzenmilch', 'kr_theme', 'kuroir', 'merbivore', 'merbivore_soft', 'mono_industrial', 'monokai', 'pastel_on_dark', 'solarized_dark', 'solarized_light', 'sqlserver', 'terminal', 'textmate', 'tomorrow', 'tomorrow_night_blue', 'tomorrow_night_bright', 'tomorrow_night_eighties', 'tomorrow_night', 'twilight', 'vibrant_ink', 'xcode'],
      selectedTheme: this.$store.state.userConfig.theme.split()[0]
    }
  },
  computed: {
    languages () {
      return Object.keys(modesByName).map(key => modesByName[key].caption).sort()
    },
    activeDocumentMode () {
      return this.activeDocument ? modesByName[this.$store.state.documents[this.activeDocument].mode] : null
    },
    ...mapGetters({
      selectedFile: 'openFiles/selectedFile'
    })
  },
  methods: {
    changeLanguage (newLanguage) {
      const mode = modes.find(mode => mode && mode.caption === newLanguage).name
      this.updateDocument({ name: this.activeDocument, mode })
    },
    changeTheme (newTheme) {
      this.selectedTheme = newTheme
      this.updateUserConfig({ theme: newTheme })
    },
    ...mapMutations({
      updateDocument: 'documents/update',
      updateUserConfig: 'userConfig/update'
    })
  }
}
</script>

<style lang="scss">

.editor-footer {
  width: 100%;
  display: flex;
  justify-content: flex-end;
  background-color: #3b4252;
}

.editor-footer-input {
  margin-bottom: 0 !important;
  margin-right: 8px;
}

.editor-footer .select {
  border-color: transparent !important;

  &::after {
    display: none !important;
  }
}

.editor-footer select {
  background-color: #3b4252 !important;
  border-color: #3b4252 !important;
  color: white !important;

  &:hover {
    background-color: lighten(#3b4252, 7) !important;
  }

  &:focus {
    outline: none !important;
  }

  option {
    color: white;
  }
}
</style>
