<template>
  <footer class="editor-footer">
    <!-- Language Selection -->
    <b-field v-if="activeDocumentMode" class="editor-footer-input">
      <b-select
        icon="web"
        :value="activeDocumentMode"
        size="is-small"
        @input="changeLanguage"
      >
        <option
          v-for="language in languages"
          :key="language"
          :value="language"
        >
          {{ language }}
        </option>
      </b-select>
    </b-field>

    <!-- Theme Selection -->
    <b-field class="editor-footer-input">
      <b-select
        icon="palette"
        :value="selectedTheme"
        size="is-small"
        @input="changeTheme"
      >
        <option
          v-for="theme in themes"
          :key="theme"
          :value="theme"
        >
          {{ theme }}
        </option>
      </b-select>
    </b-field>
  </footer>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex'
import { themesByName, themes } from '~/plugins/ace-themelist'

export default {
  name: 'EditorFooter',
  props: {
    activeDocument: {
      type: String,
      default: null
    }
  },
  data () {
    return {
      // Array generated by running command in ~/node_modules/brace/mode
      // echo \[$(for file in *; echo \'$(echo $file | cut -d '.' -f 1)\',)\]
      languages: ['abap', 'abc', 'actionscript', 'ada', 'apache_conf', 'applescript', 'asciidoc', 'assembly_x86', 'autohotkey', 'batchfile', 'bro', 'c9search', 'c_cpp', 'cirru', 'clojure', 'cobol', 'coffee', 'coldfusion', 'csharp', 'csound_document', 'csound_orchestra', 'csound_score', 'css', 'curly', 'dart', 'diff', 'django', 'd', 'dockerfile', 'dot', 'drools', 'eiffel', 'ejs', 'elixir', 'elm', 'erlang', 'forth', 'fortran', 'ftl', 'gcode', 'gherkin', 'gitignore', 'glsl', 'gobstones', 'golang', 'graphqlschema', 'groovy', 'haml', 'handlebars', 'haskell_cabal', 'haskell', 'haxe', 'hjson', 'html_elixir', 'html', 'html_ruby', 'ini', 'io', 'jack', 'jade', 'java', 'javascript', 'jsoniq', 'json', 'jsp', 'jssm', 'jsx', 'julia', 'kotlin', 'latex', 'lean', 'less', 'liquid', 'lisp', 'live_script', 'livescript', 'logiql', 'lsl', 'lua', 'luapage', 'lucene', 'makefile', 'markdown', 'mask', 'matlab', 'mavens_mate_log', 'maze', 'mel', 'mips_assembler', 'mipsassembler', 'mushcode', 'mysql', 'nix', 'nsis', 'objectivec', 'ocaml', 'pascal', 'perl', 'pgsql', 'php', 'pig', 'plain_text', 'powershell', 'praat', 'prolog', 'properties', 'protobuf', 'python', 'razor', 'rdoc', 'red', 'rhtml', 'r', 'rst', 'ruby', 'rust', 'sass', 'scad', 'scala', 'scheme', 'scss', 'sh', 'sjs', 'smarty', 'snippets', 'soy_template', 'space', 'sparql', 'sql', 'sqlserver', 'stylus', 'svg', 'swift', 'swig', 'tcl', 'tex', 'textile', 'text', 'toml', 'tsx', 'turtle', 'twig', 'typescript', 'vala', 'vbscript', 'velocity', 'verilog', 'vhdl', 'wollok', 'xml', 'xquery', 'yaml'],

      selectedTheme: themesByName[this.$store.state.userConfig.theme.split()[0]].caption
    }
  },
  computed: {
    themes () {
      return Object.keys(themesByName).map(key => themesByName[key].caption).sort()
    },
    activeDocumentMode () {
      return this.activeDocument ? this.$store.state.documents[this.activeDocument].mode : null
    },
    ...mapGetters({
      selectedFile: 'openFiles/selectedFile'
    })
  },
  methods: {
    changeLanguage (newLanguage) {
      this.updateDocument({ name: this.activeDocument, mode: newLanguage })
    },
    changeTheme (newTheme) {
      const theme = themes.find(theme => theme && theme.caption === newTheme)
      this.selectedTheme = theme.caption
      this.updateUserConfig({ theme: theme.name })
    },
    ...mapMutations({
      updateDocument: 'documents/update',
      updateUserConfig: 'userConfig/update'
    })
  }
}
</script>

<style lang="scss">

.editor-footer {
  width: 100%;
  display: flex;
  justify-content: flex-end;
  background-color: #3b4252;
}

.editor-footer-input {
  margin-bottom: 0 !important;
  margin-right: 8px;
}

.editor-footer .select {
  border-color: transparent !important;

  &::after {
    display: none !important;
  }
}

.editor-footer select {
  background-color: #3b4252 !important;
  border-color: #3b4252 !important;
  color: white !important;

  &:hover {
    background-color: lighten(#3b4252, 7) !important;
  }

  &:focus {
    outline: none !important;
  }

  option {
    color: white;
  }
}
</style>
